INSERT INTO skaters (first_name, last_name, age, years_skating)  VALUES ('Michael', 'Mote', 30, 10);
INSERT INTO skaters (first_name, last_name, age, years_skating)  VALUES ('Matthew', 'Mote', 22, 8);
INSERT INTO skaters (first_name, last_name, age, years_skating)  VALUES ('Stomping', 'Bolts', 80, 30);
INSERT INTO skaters (first_name, last_name, age, years_skating)  VALUES ('Steve', 'Steeze', 6, 3);

INSERT INTO tricks (trick_name) VALUES ('ollie');
INSERT INTO tricks (trick_name) VALUES ('shuv_it');
INSERT INTO tricks (trick_name) VALUES ('kickflip');
INSERT INTO tricks (trick_name) VALUES ('heelflip');
INSERT INTO tricks (trick_name) VALUES ('BS_180');
INSERT INTO tricks (trick_name) VALUES ('FS_180');
INSERT INTO tricks (trick_name) VALUES ('varial_kickflip');
INSERT INTO tricks (trick_name) VALUES ('360_flip');
INSERT INTO tricks (trick_name) VALUES ('nollie');
INSERT INTO tricks (trick_name) VALUES ('nollie_shuv_it');
INSERT INTO tricks (trick_name) VALUES ('fakie_ollie');
INSERT INTO tricks (trick_name) VALUES ('fakie_kickflip');
INSERT INTO tricks (trick_name) VALUES ('fakie_heelflip');
INSERT INTO tricks (trick_name) VALUES ('fakie_big_spin');
INSERT INTO tricks (trick_name) VALUES ('full_cab');
INSERT INTO tricks (trick_name) VALUES ('fakie_FS_360');

INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 1);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 2);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 3);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 4);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 5);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 6);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 7);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 8);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 9);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 10);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 11);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 12);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 13);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 14);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 15);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (1, 16);

INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (2, 1);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (2, 2);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (2, 3);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (2, 4);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (2, 5);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (2, 6);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (2, 11);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (2, 13);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (2, 14);

INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (3, 1);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (3, 2);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (3, 3);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (3, 4);

INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 1);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 2);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 3);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 4);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 5);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 6);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 7);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 8);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 9);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 10);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 11);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 12);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 13);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 14);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 15);
INSERT INTO skaters_tricks (skaters_id, tricks_id) VALUES (4, 16);
